### ISSUE TITLE
¿?¿Constructor? ¿Por qué no lo creas?

### ISSUE THREAD

**Issue by lmagarin** [Cristinaprja/Programacion#22]
https://github.com/Cristinaprja/Programacion/blob/ea3bf648ef5c267f954321fc8bc0e09414c47e8d/Examen2Trimestre/Java/Almacen/utiles/Menu.java#L8

Con tu diseño puedes usar menú sin inicializarlo. MALAMENTE

**Comment by Cristinaprja** [comment]
Ya he arreglado este problema en otro Issue
