### ISSUE TITLE
No cumple las especificaciones

### ISSUE THREAD

**Issue by lmagarin** [Cristinaprja/Programacion#24]
https://github.com/Cristinaprja/Programacion/blob/90cf43833349245f9f99cf8357115960e402aae4/Examen2Trimestre/Java/Almacen/utiles/Menu.java#L65

No cumple las especificaciones. 
https://moodle.iesgrancapitan.org/mod/assign/view.php?id=9684

> Recogerá la opción válida (entre las opciones del menú). Se usará un bucle para que devuelva una opción válida. Será privado.

**Comment by Cristinaprja** [comment]
He arreglado este Issue en el #23
